import struct

# Packet sizing
PACKET_HEADER_FORMAT = "!IIIIH"
MAX_PACKET_SIZE = 1400
MSS = MAX_PACKET_SIZE - struct.calcsize(PACKET_HEADER_FORMAT)

# Receive buffering
MAX_NETWORK_BUFFER = 65535

# Congestion control
WINDOW_INITIAL_WINDOW_SIZE = MSS
WINDOW_INITIAL_SSTHRESH = MSS * 64
DUPLICATE_ACK_THRESHOLD = 3

# Retransmission timing
DEFAULT_TIMEOUT = 3.0
MIN_RTO = 0.2
MAX_RTO = 60.0
MAX_DATA_RETRIES = 8

# Handshake and teardown
HANDSHAKE_RETRY_INTERVAL = 1.0
MAX_HANDSHAKE_RETRIES = 5
MAX_FIN_RETRIES = 5
MAX_CLOSE_DURATION = 10.0
TIME_WAIT_DURATION = 2 * DEFAULT_TIMEOUT

# RTT estimation
RTT_ALPHA = 0.125
RTT_BETA = 0.25